config/routes.rb
Rails.application.routes.draw do
  resource :voter, only: [:new, :create]

  root 'voters#new'
end

app/models/polling_location.rb
class PollingLocation < ActiveRecord::Base
  geocoded_by :address

  validates_presence_of :api_id, :name, :address, :zip, :opens_at, :closes_at

  after_validation :geocode,
    if: ->(obj){ obj.address_changed? }

  def has_early_voting?
    !early_voting_starts.nil?
  end
end

app/models/voter.rb
class Voter < ActiveRecord::Base
  geocoded_by :address

  validates_presence_of :name, :email, :birthday, :address
  validates_uniqueness_of :email

  after_validation :geocode,
    if: ->(obj){ obj.address_changed? }

  def polling_location
    PollingLocation.near(self).first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/voters_controller.rb
class VotersController < ApplicationController
  respond_to :html

  def new
    @voter = Voter.new
    respond_with @voter
  end

  def create
    @voter = Voter.create voter_params
    respond_with @voter do |format|
      format.html do
        if @voter.persisted?
          render :create
        else
          render :new
        end
      end
    end
  end

  private

  def voter_params
    params.require(:voter)
      .permit :name, :email, :address, :zip, :birthday
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t :site_name %></title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <h1><%= t :site_name %></h1>
</header>

<section>
  <%= yield %>
</section>

</body>
</html>

app/views/voters/create.html.erb
<h2><%= t(:thank_you).titleize %></h2>

<p><%= t '.success_message' %></p>

app/views/voters/new.html.erb
<%= simple_form_for @voter, url: voter_path do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>

  <%= f.input :address %>
  <%= f.input :zip %>

  <%= f.input :birthday, as: :date,
              start_year: 15.years.ago.year,
              end_year: 90.years.ago.year,
              max_years_allowed: 75 %>

  <%= f.button :submit %>
<% end %>